# -*- coding: utf-8 -*-
"""Mauricio_Portafolio1_Módulo2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MmxnCo3gd2QL3N2Ba0zso4-z009mdUP6

#Momento de Retroalimentación: Módulo 2 Implementación de una técnica de aprendizaje máquina sin el uso de un framework. (Portafolio Implementación)
Mauricio Guerrero González A01751436

###1. Implementación de un Árbol de Decisión desde Cero


El objetivo del presente código consiste en predecir si un pasajero sobrevivió al hundimiento del Titanic a partir de la implementación manual de un árbol de decisión.

###2. Importación de librerías
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""###3. Carga de los datasets

`train.csv` contiene las características de los pasajeros y la variable
objetivo `Survived`.

"""

ruta_train = "train.csv"

train = pd.read_csv(ruta_train)

print("Tamaño de train.csv:", train.shape)

print("\nTrain")
print(train.head())

#Valores faltantes
print("\nValores faltantes:")
print(train.isnull().sum())

"""###3. Identificación de la variable objetivo

La variable objetivo es `Survived`.

Esta variable representa si el pasajero sobrevivió, donde 0 significa que no sobrevivió y 1 representa que si sobrevivió

"""

print(train["Survived"].value_counts())

print("\nProporción:")
print(train["Survived"].value_counts(normalize=True))

"""###5. Preparación de los datos


Se utiliza `Sex` porque es una variable importante del dataset, pero se transforma manualmente:

- 0: male
- 1: female

También se construyen:

- `FamilySize`: tamaño de la familia.
- `IsAlone`: indica si el pasajero viajaba solo.

Estas se generan tomando en consideración las variables `SibSp`(Siblings + Spouses) y `Parch` (Parents + Children)
"""

def preparar_datos(df):
    # Construye variables sencillas que puedan aportar información al clasificador.
    datos = df.copy()

    datos["Sex"] = datos["Sex"].map({
        "male": 0,
        "female": 1
    })

    datos["FamilySize"] = (
        datos["SibSp"] + datos["Parch"] + 1
    )

    datos["IsAlone"] = (
        datos["FamilySize"] == 1
    ).astype(int)

    columnas = [
        "Pclass",
        "Sex",
        "Age",
        "SibSp",
        "Parch",
        "Fare",
        "FamilySize",
        "IsAlone"
    ]

    return datos[columnas]

X = preparar_datos(train)
y = train["Survived"].to_numpy()

print(X.head())

"""###6. Separación de entrenamiento y prueba

Separa `train.csv` en:

- 80 % para entrenamiento.
- 20 % para prueba.

"""

def separar_datos(X, y, porcentaje=0.8, semilla=42):
    # Mezcla los datos y conserva una división reproducible entre entrenamiento y prueba.
    rng = np.random.default_rng(semilla)

    indices = np.arange(len(X))
    rng.shuffle(indices)

    punto = int(len(X) * porcentaje)

    train_idx = indices[:punto]
    test_idx = indices[punto:]

    return (
        X.iloc[train_idx].reset_index(drop=True),
        X.iloc[test_idx].reset_index(drop=True),
        y[train_idx],
        y[test_idx]
    )

X_train, X_test, y_train, y_test = separar_datos(
    X,
    y
)

print("Entrenamiento:", X_train.shape)
print("Prueba:", X_test.shape)

"""##7. Valores faltantes

Reemplaza los valores faltantes de las variables numéricas con la mediana calculada a partir del conjunto de entrenamiento.
"""

# Calcula las medianas únicamente con los datos de entrenamiento.
medianas = X_train.median()

X_train = X_train.fillna(medianas)
X_test = X_test.fillna(medianas)

print("Valores faltantes en entrenamiento:")
print(X_train.isnull().sum())

print("\nValores faltantes en prueba:")
print(X_test.isnull().sum())

"""###8. Índice Gini

El índice Gini mide qué tan mezcladas están las clases dentro de un nodo, donde un nodo completamente puro tiene un índice Gini igual a 0.
"""

def gini(y):
    # Calcula la impureza de las clases presentes en un nodo.
    _, conteos = np.unique(y, return_counts=True)
    proporciones = conteos / len(y)

    return 1 - np.sum(proporciones ** 2)

"""###9. Búsqueda de la mejor división

Para cada variable prueba distintos puntos de corte. La mejor división será aquella que produzca el menor Gini después de separar
los datos.
"""

def mejor_division(X, y, min_hoja=15):
    # Identifica la variable y el umbral que producen la mayor reducción de impureza.
    mejor_gini = float("inf")
    mejor_variable = None
    mejor_umbral = None

    for variable in X.columns:

        valores = X[variable].to_numpy()

        candidatos = np.unique(
            np.percentile(
                valores,
                np.linspace(5, 95, 19)
            )
        )

        for umbral in candidatos:

            izquierda = valores <= umbral
            derecha = ~izquierda

            if (
                izquierda.sum() < min_hoja
                or derecha.sum() < min_hoja
            ):
                continue

            y_izq = y[izquierda]
            y_der = y[derecha]

            gini_division = (
                len(y_izq) * gini(y_izq)
                + len(y_der) * gini(y_der)
            ) / len(y)

            if gini_division < mejor_gini:
                mejor_gini = gini_division
                mejor_variable = variable
                mejor_umbral = umbral

    return mejor_variable, mejor_umbral, mejor_gini

"""###10. Construcción del árbol

En cada nodo:

1. Identifica la mejor división.
2. Separa los datos.
3. Construye las ramas.
4. Repite el proceso.

El proceso termina cuando se alcanza la profundidad máxima, existen pocas observaciones o el nodo ya es puro.
"""

class ArbolDecision:

    def __init__(
        self,
        max_depth=4,
        min_samples=30,
        min_hoja=15
    ):
        self.max_depth = max_depth
        self.min_samples = min_samples
        self.min_hoja = min_hoja
        self.arbol = None

    def construir(self, X, y, profundidad=0):
        # Construye recursivamente los nodos y hojas del árbol.
        clase = int(np.bincount(y).argmax())

        if (
            profundidad >= self.max_depth
            or len(y) < self.min_samples
            or gini(y) == 0
        ):
            return {
                "tipo": "hoja",
                "clase": clase
            }

        variable, umbral, gini_nuevo = mejor_division(
            X,
            y,
            self.min_hoja
        )

        if variable is None:
            return {
                "tipo": "hoja",
                "clase": clase
            }

        izquierda = X[variable] <= umbral
        derecha = ~izquierda

        return {
            "tipo": "decision",
            "variable": variable,
            "umbral": umbral,
            "izquierda": self.construir(
                X[izquierda].reset_index(drop=True),
                y[izquierda],
                profundidad + 1
            ),
            "derecha": self.construir(
                X[derecha].reset_index(drop=True),
                y[derecha],
                profundidad + 1
            )
        }

    def fit(self, X, y):
        # Inicia la construcción del árbol desde el nodo raíz.
        self.arbol = self.construir(
            X.reset_index(drop=True),
            np.asarray(y)
        )

    def predecir_uno(self, fila, nodo):
        # Recorre las ramas hasta encontrar la hoja correspondiente a la observación.
        if nodo["tipo"] == "hoja":
            return nodo["clase"]

        if fila[nodo["variable"]] <= nodo["umbral"]:
            return self.predecir_uno(
                fila,
                nodo["izquierda"]
            )

        return self.predecir_uno(
            fila,
            nodo["derecha"]
        )

    def predict(self, X):
        # Genera una predicción para cada observación.
        return np.array([
            self.predecir_uno(fila, self.arbol)
            for _, fila in X.iterrows()
        ])

    def imprimir(self, nodo=None, espacio=""):
        # Recorre el árbol para mostrar las reglas y las clases de las hojas.
        if nodo is None:
            nodo = self.arbol

        if nodo["tipo"] == "hoja":
            resultado = (
                "Sobrevive"
                if nodo["clase"] == 1
                else "No sobrevive"
            )

            print(
                espacio
                + "→ "
                + resultado
                + f" ({nodo['clase']})"
            )
            return

        print(
            espacio
            + f"{nodo['variable']} <= "
            + f"{nodo['umbral']:.2f}"
        )

        print(espacio + "├── Sí:")
        self.imprimir(
            nodo["izquierda"],
            espacio + "│   "
        )

        print(espacio + "└── No:")
        self.imprimir(
            nodo["derecha"],
            espacio + "    "
        )

"""###11. Entrenamiento del árbol

Se limita la profundidad para obtener un árbol sencillo y evitar que memorice todos los datos.
"""

arbol = ArbolDecision(
    max_depth=4,
    min_samples=30,
    min_hoja=15
)

arbol.fit(
    X_train,
    y_train
)

"""###12. Estructura del árbol

"""

print("=" * 60)
print("ÁRBOL DE DECISIÓN")
print("=" * 60)

arbol.imprimir()

"""###13. Generación de predicciones

Utiliza el árbol para clasificar tanto las observaciones de entrenamiento como
las observaciones de prueba.
"""

pred_train = arbol.predict(X_train)
pred_test = arbol.predict(X_test)

print("Primeras 20 predicciones:")
print(pred_test[:20])

print("\nPrimeras 20 clases reales:")
print(y_test[:20])

"""###14. Matriz de confusión

Construye la matriz de confusión.

"""

def matriz_confusion(y_real, y_pred):
    # Cuenta manualmente los cuatro posibles resultados de la clasificación.
    TN = np.sum((y_real == 0) & (y_pred == 0))
    FP = np.sum((y_real == 0) & (y_pred == 1))
    FN = np.sum((y_real == 1) & (y_pred == 0))
    TP = np.sum((y_real == 1) & (y_pred == 1))

    return TP, FP, FN, TN

"""###15. Métricas de evaluación

Calcula las métricas principales de clasificación.
"""

def metricas(y_real, y_pred):
    # Calcula las métricas a partir de los cuatro componentes de la matriz.
    TP, FP, FN, TN = matriz_confusion(
        y_real,
        y_pred
    )

    accuracy = (
        (TP + TN)
        / (TP + TN + FP + FN)
    )

    precision = (
        TP / (TP + FP)
        if TP + FP > 0
        else 0
    )

    recall = (
        TP / (TP + FN)
        if TP + FN > 0
        else 0
    )

    f1 = (
        2 * precision * recall
        / (precision + recall)
        if precision + recall > 0
        else 0
    )

    matriz = np.array([
        [TP, FP],
        [FN, TN]
    ])

    return matriz, accuracy, precision, recall, f1

"""###16. Evaluación del modelo

Compara el desempeño del árbol sobre entrenamiento y prueba, además se despliega la matriz de confusión final.
"""

resultados_train = metricas(y_train, pred_train)

resultados_test = metricas(y_test,pred_test)

print("ENTRENAMIENTO")

print(f"Accuracy : {resultados_train[1]:.4f}")
print(f"Precision: {resultados_train[2]:.4f}")
print(f"Recall   : {resultados_train[3]:.4f}")
print(f"F1-score : {resultados_train[4]:.4f}")


print("\nPRUEBA")


print(f"Accuracy : {resultados_test[1]:.4f}")
print(f"Precision: {resultados_test[2]:.4f}")
print(f"Recall   : {resultados_test[3]:.4f}")
print(f"F1-score : {resultados_test[4]:.4f}")

matriz_test = resultados_test[0]

plt.figure(figsize=(7, 6))

plt.imshow(matriz_test)

plt.colorbar()

plt.xticks(
    [0, 1],
    ["Yes", "No"]
)

plt.yticks(
    [0, 1],
    ["Yes", "No"]
)

plt.xlabel("Valores reales")
plt.ylabel("Valores predichos")

plt.title("Matriz de Confusión")

for i in range(2):
    for j in range(2):

        if i == 0 and j == 0:
            texto = "True Positive"

        elif i == 0 and j == 1:
            texto = "False Positive"

        elif i == 1 and j == 0:
            texto = "False Negative"

        else:
            texto = "True Negative"

        plt.text(
            j,
            i,
            f"{texto}\n\n{matriz_test[i, j]}",
            ha="center",
            va="center"
        )

plt.tight_layout()
plt.show()

"""##17. Predicciones"""

ejemplos = X_test.head(15).copy()

ejemplos["Real"] = y_test[:15]
ejemplos["Prediccion"] = pred_test[:15]

ejemplos["Correcta"] = (
    ejemplos["Real"]
    == ejemplos["Prediccion"]
)

print(ejemplos)
